Repository caarlos0/go-gumroad, pull requests merged in 2022-04, with the labels that each got.

#1 HTTPS hardening
  generate_cert.go
  main.go
  main_test.go
  testdata/ca.pem
  testdata/mitm.pem
Labels: size/L

#6 fix: correct JSON key in Purchase struct
  main.go
Labels: size/XS

#7 feat: return early if product or key is blank
  main.go
  main_test.go
Labels: size/M

#8 test: add BenchmarkErrors
  main_test.go
Labels: size/L

#10 feat: Encapsulate http.Client, API endpoint, and product in struct
  generate_cert.go
  main.go
  main_test.go
  testdata/ca.pem
  testdata/mitm.pem
Labels: enhancement, size/XL
